global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: oauth2-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - oauth2_server:8080

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

rule_files:
  - /etc/prometheus/rules/*.yml
