[package]
name = "oauth2-openapi"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
oauth2-core = { path = "../oauth2-core", features = ["openapi"] }
utoipa = { version = "5.4", features = ["chrono", "uuid"] }
