apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

replicas:
  - name: oauth2-server
    count: 1

images:
  - name: docker.io/ianlintner068/oauth2-server
    newTag: dev
